### PR TITLE
Rematch5 fixups

### LINKED ISSUE #63: Bug: Wrong for loop expresion.
the iterator expression should be a method call not a ipairs function

https://github.com/axc450/pbs/blob/88e719b760d2c81b6a416453443f8bd847abb687/Rematch/Addon.lua#L40

should be `for key, script in self:IterateScripts() do`

### PR DESCRIPTION
**Pull request by bloerwald**
- removes localisation placeholders 
- Closes #63

### CODE REVIEW

File: Rematch/Addon.lua [hunk 1]
```diff
@@ -72,20 +72,22 @@ function RematchPlugin:OnEnable()
...
-            -- the script of the "modified" team id.
-            local modified = newTeamID
-            local withDataFrom = oldTeamID
-
-            if not modified or not self:GetScript(modified) then
-                return
+        Rematch.events:Register(self, 'REMATCH_TEAM_OVERWRITTEN', function(self, teamID, overwriteID)
+            -- teamID is being overwritten with import, and wont have a script
+            if teamID and not overwriteID then
+                return self:RemoveScript(teamID)
```
Comment (gizzmo) [inline Rematch/Addon.lua:78]: These arguments need to swap. 
```lua 
Rematch.events:Register(self, 'REMATCH_TEAM_OVERWRITTEN', function(self, overwriteID, teamID)
    -- overwriteID is being overwritten with import, and wont have a script
    if overwriteID and not teamID then
        return self:RemoveScript(overwriteID)
```
the remaining callback looks good

**Review by axc450 — APPROVED** [review]

File: Rematch/Addon.lua (hunk 1 above)
Comment (bloerwald) [reply Rematch/Addon.lua:78]: #66
